// Verifies the path that the AGENTS.md block generated by `next dev` tells
// agents to read. Run AFTER `yarn dev` has generated AGENTS.md.
import fs from 'node:fs'

const agents = fs.readFileSync('AGENTS.md', 'utf8')
const match = agents.match(/`(node_modules\/next\/dist\/docs\/)`/)
console.log('instructed docs path:', match ? match[1] : '(not found in AGENTS.md)')
const p = match ? match[1] : 'node_modules/next/dist/docs/'
console.log('exists on disk:', fs.existsSync(p))
console.log(
  'markdown guides found:',
  fs.existsSync(p) ? fs.readdirSync(p).length : 0
)
