import { chromium } from '@playwright/test'
const dir = '/workspace/.next-maintainer/reproduction-artifacts/playwright'
const b = await chromium.launch()
const ctx = await b.newContext()
await ctx.addCookies([{ name: 'session', value: 'user-1', url: 'http://localhost:3000' }])
const p = await ctx.newPage()
const logs = []
p.on('console', (m) => logs.push(`[console:${m.type()}] ${m.text().slice(0, 600)}`))
p.on('pageerror', (e) => logs.push(`[pageerror] ${e.message.slice(0, 600)}`))
p.on('requestfailed', (r) => logs.push(`[requestfailed] ${r.url()} ${r.failure()?.errorText}`))
p.on('response', (r) => {
  const u = r.url()
  if (r.status() >= 400) logs.push(`[http ${r.status()}] ${u}`)
  else if (/shiki|mermaid|highlight|lazy-compilation/.test(u)) logs.push(`[http ${r.status()}] ${u.slice(0, 180)}`)
})
await p.goto('http://localhost:3000/', { waitUntil: 'load' })
await p.screenshot({ path: `${dir}/1-initial.png`, fullPage: true })
await p.click('#open')
await p.waitForTimeout(45000)
await p.screenshot({ path: `${dir}/2-after-open.png`, fullPage: true })
logs.push('--- body after open ---')
logs.push((await p.locator('body').innerText()).replace(/\n+/g, ' | ').slice(0, 1200))
logs.push('--- svg count: ' + (await p.locator('svg').count()))
console.log(logs.join('\n'))
await b.close()
